/*
 Author: Emma Kimlin
 Title: main.cpp
 Date Created: 3.2.2016
 Description: This program simulates Process Control of an OS where interrupts and system calls are generated by user input.
                Read Queue scheduler uses Pre-emptive Short-Come-First algorithm. Device queues, including disk queue, use FIFO. 
 Build: make
 */

#include <iostream>
#include "Scheduler.h"
#include <time.h>
#include <stdlib.h>


int main() {
/****SYSTEM GENERATION******/
    Scheduler my_system;
/********RUNNING***********/
    std::string user_input;
    srand (time(0));
    while (true)
    {
        std::cin >> user_input;
        if (user_input == "A")
            my_system.AddNewProcess();
        else if (user_input == "t")
            my_system.TerminateProcessInCPU();
        else if (user_input == "S")
            my_system.Snapshot();
        else
            my_system.ParseCommand(user_input);
    }
    return 0;
}
























